# serverless.yml

service: userappback

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  crearcliente:
    handler: app.handler
    events:
      - http: 'POST /cliente/crearcliente'
  listclientes:
    handler: app.handler
    events:
      - http: 'GET /cliente/listclientes'
  kpideclientes:
    handler: app.handler
    events:
      - http: 'GET /cliente/kpideclientes'